from __future__ import annotations

from typing import Any, Protocol


class MapDataProvider(Protocol):
    def provenance(self) -> dict[str, Any]: ...
    def get_tree(self, refresh: bool = False) -> list[dict[str, Any]]: ...
    def get_map(self, map_id: str, refresh: bool = False) -> dict[str, Any] | None: ...
    def get_points(
        self,
        map_id: str,
        semantic_key: str | None = None,
        label_id: str | None = None,
        refresh: bool = False,
    ) -> list[dict[str, Any]]: ...
    def get_labels(self, map_id: str, refresh: bool = False) -> list[dict[str, Any]] | None: ...
    def get_point(self, core_point_id: int, refresh: bool = False) -> dict[str, Any] | None: ...
